### ISSUE TITLE
Nanoleaf Skylight?

### ISSUE THREAD

**Issue by gregor-hh** [daniel-2k/ioBroker.nanoleaf-lightpanels#132]
Hello,

thx for the plugin.

Question:

are also the Nanoleaf Skylights supported, or will be?

Best regards

**Comment by daniel-2k** [comment]
Hello,

I can add this device type. But I do not have such a device and so I need the device information from the info endpoint.
If you can do a GET request to the device to retrieve this info, then I can add it.
But if the adapter does not recognize the model, it falls back to Canvas device.
So you should also be able to connect and to retrieve an authorization token.
You can then us this and can call the following URL in a browser:

http://<your device IP / hostname>:16021/api/v1/<your auth token>

**Comment by stefanerdmann** [comment]
{
    "name": "Skylight 5554",
    "serialNo": "SXXXXXXXXX",
    "manufacturer": "Nanoleaf",
    "firmwareVersion": "10.0.8",
    "hardwareVersion": "1.4-1",
    "model": "NL64",
    "discovery": {},
    "effects": {
        "effectsList": [
            "Blue Skies",
            "Cosmic Galaxy",
            "Full Moon",
            "Gentle Rain",
            "Golden Hour",
            "Late Night",
            "Midnight Mood",
            "Molten Sunrise",
            "Mountain Air",
            "Northern Lights",
            "Shooting Stars",
            "Sun Shower"
        ],
        "select": "*Solid*"
    },
    "firmwareUpgrade": {},
    "panelLayout": {
        "globalOrientation": {
            "value": 0,
            "max": 360,
            "min": 0
        },
        "layout": {
            "numPanels": 3,
            "sideLength": 180,
            "positionData": [
                {
                    "panelId": 48997,
                    "x": 90,
                    "y": 180,
                    "o": 0,
                    "shapeType": 31
                },
                {
                    "panelId": 22836,
                    "x": 180,
                    "y": 0,
                    "o": 270,
                    "shapeType": 30
                },
                {
                    "panelId": 28193,
                    "x": 0,
                    "y": 0,
                    "o": 180,
                    "shapeType": 30
                }
            ]
        }
    },
    "qkihnokomhartlnp": {},
    "schedules": {},
    "state": {
        "brightness": {
            "value": 49,
            "max": 100,
            "min": 0
        },
        "colorMode": "ct",
        "ct": {
            "value": 2703,
            "max": 6500,
            "min": 2700
        },
        "hue": {
            "value": 28,
            "max": 360,
            "min": 0
        },
        "on": {
            "value": true
        },
        "sat": {
            "value": 66,
            "max": 100,
            "min": 0
        }
    }
}

**Comment by daniel-2k** [comment]
I added Skylight to latest version 1.5.0.
Please check out.

**Comment by stefanerdmann** [comment]
Thank you. It will take some time until I can test it, as I unmounted the ceiling light. Probably next month.

**Comment by stefanerdmann** [comment]
Hi, sry for the late reply but I just managed to install the lights. It seems like your implementation works.
