### ISSUE TITLE
Update stable version in repo to 0.8.2

### ISSUE THREAD

**Issue by GermanBluefox** [daniel-2k/ioBroker.nanoleaf-lightpanels#14]
# Think about update stable version to 0.8.2
**Version**: stable=**0.8.1** (398 days old) => latest=**0.8.2** (215 days old)
**Installs**: stable=**144** (58.78%), latest=**95** (38.78%), total=**245**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L847)

**Comment by Sacred-Shadow** [comment]
@daniel-2k wird langsam Zeit oder? :) Nu 3 Monate später :D

**Comment by daniel-2k** [comment]
Ist irgendwie untergegangen. Da ich aber sowieso an der Version 1.0.0 gearbeitet habe, habe ich es jetzt auch nicht mehr gemacht.
Siehe 1.0.0 im latest. Wenn die gut läuft, geht die ins stable.

**Comment by daniel-2k** [comment]
adapter is in stable with version 1.0.6
