### ISSUE TITLE
Fehler Adapter 1.0.2

### ISSUE THREAD

**Issue by FlexerJR** [daniel-2k/ioBroker.nanoleaf-lightpanels#17]
Hallo Daniel2k, leider gibt es immer noch Probleme bei dem Adapter. Version 1.0.2
Hier die Log Meldung. Adapter wechselt mehrmals von Grün auf Gelb zurück auf Grün und wieder Gelb.
nanoleaf-lightpanels.0 | 2020-07-09 10:00:53.690 | warn | (20634) Connection to '10.10.10.16:16021' lost, Error: No ssdp:alive detected. Try to reconnect...
-- | -- | -- | --

**Comment by daniel-2k** [comment]
Welche nanoleafs hast du? Light Panels oder Canvas?
Also dieses Problem hatten ja jetzt schon mehrere. In den ersten 1.0.x Versionen war das ein Problem im Adapter wegen Canvas. Der Rest waren jetzt eigentlich immer Netzwerk-/Firewallgeschichten.
Kannst du mal die Test-Version installieren: https://github.com/daniel-2k/ioBroker.nanoleaf-lightpanels/tarball/test
Das Log auf Debug stellen und schauen, ob überhaupt SSDP-Pakete im Adapter ankommen?
Vlt. hast du ja dasselbe Problem wie stefande im Forum. Seine Canvas senden SSDP:alive Pakete, aber nach einer gewissen Zeit plötzlich nicht mehr. Kannst ja dann als zweites auch mal deine nanoleafs vom Stromnetz nehmen und wieder einschalten und schauen, ob es dann wieder geht, und wenn ja, wie lange.

**Comment by FlexerJR** [comment]
Ja sind Canvas Panels. Ok alles klar werde deinen Lösungsweg versuchen und berichten jedoch schaffe ich das erst morgen. Viele Grüsse melde mich

**Comment by FlexerJR** [comment]
Hallo Hier nochmal schnell die Logmeldungen im Debug Mode. Werde jetzt deine Test Version installieren. 

nanoleaf-lightpanels.0 | 2020-07-11 09:49:34.044 | debug | (23412) Connect timer started with 60000 ms
-- | -- | -- | --
nanoleaf-lightpanels.0 | 2020-07-11 09:49:34.043 | debug | (23412) SSE connection closed!
nanoleaf-lightpanels.0 | 2020-07-11 09:49:34.043 | debug | (23412) Command queue cleared!
nanoleaf-lightpanels.0 | 2020-07-11 09:49:34.043 | debug | (23412) Polling timer stopped!
nanoleaf-lightpanels.0 | 2020-07-11 09:49:34.043 | warn | (23412) Connection to '10.10.10.16:16021' lost, Error: No ssdp:alive detected. Try to reconnect...
nanoleaf-lightpanels.0 | 2020-07-11 09:48:19.063 | debug | (23412) SSE subscription started, listening...
nanoleaf-lightpanels.0 | 2020-07-11 09:48:19.034 | debug | (23412) nanoleaf Device "Canvas" (NL29) detected!
nanoleaf-lightpanels.0 | 2020-07-11 09:48:19.033 | info | (23412) Connected to "10.10.10.16:16021"
nanoleaf-lightpanels.0 | 2020-07-11 09:48:19.033 | debug | (23412) Connect timer stopped!
nanoleaf-lightpanels.0 | 2020-07-11 09:48:18.977 | info | (23412) Connecting to "10.10.10.16:16021"...
nanoleaf-lightpanels.0 | 2020-07-11 09:48:18.977 | debug | (23412) SSDP events initialized!
nanoleaf-lightpanels.0 | 2020-07-11 09:48:18.976 | info | (23412) Nanoleaf adapter "nanoleaf-lightpanels.0" started.
nanoleaf-lightpanels.0 | 2020-07-11 09:48:18.963 | info | (23412) starting. Version 1.0.2 in /opt/iobroker/node_modules/iobroker.nanoleaf-lightpanels, node: v10.19.0, js-controller: 3.1.6
nanoleaf-lightpanels.0 | 2020-07-11 09:48:15.069 | info | (20634) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
nanoleaf-lightpanels.0 | 2020-07-11 09:48:15.068 | info | (20634) terminating
nanoleaf-lightpanels.0 | 2020-07-11 09:48:15.068 | info | (20634) Shutting down Nanoleaf adapter "nanoleaf-lightpanels.0"...
nanoleaf-lightpanels.0 | 2020-07-11 09:48:15.067 | info | (20634) Got terminate signal TERMINATE_YOURSELF
nanoleaf-lightpanels.0 | 2020-07-11 09:47:47.813 | info | (20634) Reconnected to "10.10.10.16:16021"

**Comment by daniel-2k** [comment]
Funktioniert das inzwischen? Die Geschichte ging im Forum weiter, oder? Hab jetzt nicht mehr so den Überblick.
Ich würde das Issue sonst schließen.
